coursebuilder/urls.py
from django.conf.urls import url

from . import views

app_name = "coursebuilder"


urlpatterns = [
    url(r"^$", views.landing_page, name="landing_page"),
    url(r"^coursebuilder/landing_page/", views.landing_page, name="landing_page"),
    url(r"^coursebuilder/chapter/(?P<chapter>\D+)/$", views.chapter, name="chapter"),
    url(r"^coursebuilder/dynamic_about/*$", views.dynamic_about, name="dynamic_about"),
    url(r"^coursebuilder/dynamic_gloss/*$", views.dynamic_gloss, name="dynamic_gloss"),
    url(r"^coursebuilder/parse_search/*$", views.parse_search, name="parse_search"),
    url(r"^coursebuilder/grade_quiz/*$", views.grade_quiz, name="grade_quiz"),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"", include("coursebuilder.urls")),
    url(r"^tinymce/", include("tinymce.urls")),
]

admin.site.site_header = "CourseBuilder Administration"
admin.site.site_title = "CourseBuilder Admin"
admin.site.index_title = "Welcome to the CourseBuilder Admin"

coursebuilder/models.py
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField


QUEST_LEN = 256
ANS_LEN = 128
MODNM_LEN = 16
DEF_PASS = 80.0

QTYPES = (
    ("MCHOICE", "Multiple choice"),
    ("TF", "True/False"),
    ("BLANK", "Fill-in-the-blank"),
    ("ESSAY", "Essay"),
)


class CourseModule(models.Model):
    """
    This table holds the modules (chapters) of our course.
    The content field should only have the intro material:
        the section contents go in the ModuleSection table.
    """

    course_order = models.IntegerField(blank=True, null=True, unique=True)
    module = models.CharField(max_length=MODNM_LEN, unique=True)
    title = models.TextField()
    next_module = models.CharField(max_length=MODNM_LEN)
    content = HTMLField(default="Please enter your contents here!")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["course_order"]


class ModuleSection(models.Model):
    """
    This table holds the section content for each module (chapter)
    in our material.
    """

    module = models.ForeignKey(CourseModule, models.SET_NULL, blank=True, null=True)
    title = models.TextField()
    order = models.IntegerField(blank=False, null=False)
    lesson_order = models.IntegerField(blank=True, null=True)
    content = HTMLField(default="Please enter your contents here!")

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ("module", "order")
        ordering = ["module", "order"]


class Quiz(models.Model):
    # module = models.CharField(max_length=MODNM_LEN, unique=True)
    module = models.ForeignKey(CourseModule, models.SET_NULL, blank=True, null=True)
    minpass = models.FloatField(default=DEF_PASS)
    numq = models.IntegerField()
    show_answers = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Quizzes"

    def __str__(self):
        return "Quiz for " + str(self.module)


class Question(models.Model):
    # module = models.CharField(max_length=MODNM_LEN)
    module = models.ForeignKey(CourseModule, models.SET_NULL, blank=True, null=True)
    text = models.CharField(max_length=QUEST_LEN)
    difficulty = models.IntegerField(null=True, blank=True)
    qtype = models.CharField(choices=QTYPES, max_length=10)
    correct = models.CharField(max_length=1)
    answerA = models.CharField(max_length=ANS_LEN, null=True, blank=True)
    answerB = models.CharField(max_length=ANS_LEN, null=True, blank=True)
    answerC = models.CharField(max_length=ANS_LEN, null=True, blank=True)
    answerD = models.CharField(max_length=ANS_LEN, null=True, blank=True)
    answerE = models.CharField(max_length=ANS_LEN, null=True, blank=True)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ["module", "qtype", "difficulty"]


class Extras(models.Model):
    title = models.TextField()
    content = HTMLField(default="Please enter your contents here!")

    class Meta:
        verbose_name_plural = "Extras"

    def __str__(self):
        return self.title


class Grade(models.Model):
    quiz = models.ForeignKey(Quiz, related_name="quiz", on_delete=models.DO_NOTHING)
    score = models.DecimalField(max_digits=5, decimal_places=2)
    participant = models.ForeignKey(
        User, related_name="participant", on_delete=models.DO_NOTHING
    )
    record_date = models.DateTimeField(auto_now=True)
    quiz_name = models.CharField(max_length=MODNM_LEN, default="work")

coursebuilder/views.py
import urllib.request
import re
import random

from django.http import request, HttpResponseServerError, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string
from bs4 import BeautifulSoup as bs
from decimal import Decimal

from .models import CourseModule, ModuleSection, Question, Quiz, Grade, Extras


DEF_NUM_RAND_QS = 10  # total number of questins
site_hdr = "CourseBuilder"


def landing_page(request: request) -> object:

    try:
        modules = CourseModule.objects.all().order_by("course_order")
        messageContent = "Course Modules"
        return render(
            request,
            "landing_page.html",
            {"modules": modules, "header": site_hdr, "message": messageContent},
        )
    except Exception:
        messageContent = "Database Not Connected"
        return render(
            request,
            "landing_page.html",
            {"header": site_hdr, "message": messageContent},
        )


def dynamic_about(request: request) -> object:
    try:
        return render(
            request,
            "dynamic_about.html",
            {"header": site_hdr, "about": render_to_string("about.html")},
        )

    except Exception:
        return render(
            request,
            "dynamic_about.html",
            {"header": site_hdr, "message": "Database Not Connected"},
        )


def chapter(request, chapter="basics"):

    try:
        contents = CourseModule.objects.get(module=chapter)
        sections = ModuleSection.objects.filter(module=contents).order_by(
            "order", "lesson_order"
        )
        rand_qs = get_quiz_question(contents)
        next_module = ""
        if not rand_qs:
            try:
                if CourseModule.objects.get(module=contents.next_module):
                    next_module = contents.next_module
            except Exception:
                pass
        return render(
            request,
            "chapter.html",
            {
                "module_title": contents.title,
                "sections": sections,
                "questions": rand_qs,
                "header": site_hdr,
                "content": contents.content,
                "mod_nm": chapter,
                "next_module": next_module,
            },
        )
    except Exception:
        return render(
            request,
            "chapter.html",
            {"header": site_hdr, "content": "Database Not Connected"},
        )


def dynamic_gloss(request: request) -> object:
    try:
        gloss = Extras.objects.get(title="Gloss")
        return render(
            request, "dynamic_gloss.html", {"header": site_hdr, "gloss": gloss.content}
        )
    except Exception:
        return render(
            request,
            "dynamic_gloss.html",
            {"header": site_hdr, "message": "Database Not Connected"},
        )


@require_http_methods(["GET", "POST"])
def parse_search(request) -> object:
    def crawl_index(url):
        with urllib.request.urlopen(url) as response:
            html = response.read()
            html = bs(html, "html.parser")
            lst = bs.find_all(html, "a")
            url_lst = []
            for i in lst:
                web_url = i["href"]
                if "/coursebuilder/" in web_url:
                    url_lst.append(web_url)
            return url_lst

    def search_page(url_lst, query):
        result = []
        for i in url_lst:
            content_url = url + i
            with urllib.request.urlopen(content_url) as res:

                html = res.read()
                html = bs(html, "html.parser")
                strings = html.body.strings
                title = html.h1
                if title is None:
                    title = i.split("/")[-1]
                else:
                    title = re.sub("[\n]", "", title.string).strip()
                for i in strings:
                    i = re.sub("\n", " ", i)
                    if query in i.lower():
                        dic = {"url": content_url, "page": title, "content": i}
                        result.append(dic)
        return result

    url = "http://www.thecoursebuildercourse.com"

    try:
        header = "The coursebuilder Course"
        path = request.get_full_path()
        query = path.split("query=")[1]
        if ("+") in query:
            query = " ".join(query.split("+")).lower()
        else:
            query = query.lower()

        data = search_page(crawl_index(url), query)

        return render(
            request, "search.html", dict(data=data, header=header, query=query)
        )
    except Exception as e:
        return HttpResponseServerError(e.__cause__, e.__context__, e.__traceback__)


def get_nav_links(curr_module, correct_pct, curr_quiz, mod_nm):
    nav_links = {}
    # show link to next module if it exists
    if curr_module is not None:
        try:
            if CourseModule.objects.get(module=curr_module.next_module):
                nav_links = {"next": curr_module.next_module}
        except Exception:
            nav_links = {}
        # If user fails, show link to previous module
        if correct_pct < curr_quiz.minpass:
            nav_links["previous"] = mod_nm
    return nav_links


def get_quiz_question(mod_nm):

    # Returns list of Randomized Questions
    # :param: mod_nm, module name
    # :return: list() containing randomized questions, mod_nm
    try:
        rand_qs = []
        questions = Question.objects.filter(module=mod_nm)
        total_num_questions = len(questions)
        num_qs_to_randomize = DEF_NUM_RAND_QS

        if total_num_questions > 0:
            # we have to fetch numq from here:
            quizzes = Quiz.objects.filter(module=mod_nm)

            # we should log if we get count > 1 here!
            for quiz in quizzes:
                # we should have only 1 if any!
                num_qs_to_randomize = quiz.numq
                break

            if total_num_questions >= num_qs_to_randomize:
                rand_qs = random.sample(list(questions), num_qs_to_randomize)
            else:
                rand_qs = random.sample(list(questions), total_num_questions)

        return rand_qs

        # And if we crashed along the way - we crash gracefully...
    except Exception:
        return render(
            request,
            "chapter.html",
            {"header": site_hdr, "content": "Database Not Connected"},
        )


def mark_quiz(user_answers, graded_answers):
    num_correct = 0

    for answered_question in user_answers:
        processed_answer = {}
        id_to_retrieve = next(iter(answered_question))
        original_question = get_object_or_404(Question, pk=id_to_retrieve)

        # Lets start building a dictionary
        # with the status for the particular questions.
        processed_answer["question"] = original_question.text
        processed_answer["correctAnswer"] = original_question.correct.lower()
        processed_answer["yourAnswer"] = answered_question[id_to_retrieve]

        correctanskey = "answer{}".format(processed_answer["correctAnswer"].upper())
        youranskey = "answer{}".format(processed_answer["yourAnswer"].upper())

        processed_answer["correctAnswerText"] = getattr(
            original_question, correctanskey
        )
        processed_answer["yourAnswerText"] = getattr(original_question, youranskey)

        # and now we are evaluating either as right or wrong...
        if answered_question[id_to_retrieve] == processed_answer["correctAnswer"]:
            processed_answer["status"] = "right"
            num_correct += 1
        else:
            processed_answer["message"] = "Sorry, that's incorrect!"
            processed_answer["status"] = "wrong"
            # and store to ship to the Template.
        graded_answers.append(processed_answer)
    return num_correct


def grade_quiz(request):
    """
    :param request: request as HttpRequest()
    Returns an html page containing results of quiz.
    """
    try:
        num_rand_qs = DEF_NUM_RAND_QS
        # First, we process only when form is POSTed...
        if request.method == "POST":
            graded_answers = []
            user_answers = []
            form_data = request.POST
            num_correct = 0

            # get only post fields containing user answers...
            for key, value in form_data.items():
                # what is going on here is completely obscure to me: GC
                if key.startswith("_"):
                    proper_id = str(key).strip("_")
                    user_answers.append({proper_id: value})

            # forces user to answer all quiz questions,
            # redirects to module page if not completed
            mod_nm = form_data["submit"]
            contents = CourseModule.objects.get(module=mod_nm)
            questions = Question.objects.filter(module=contents)

            quizzes = Quiz.objects.filter(module=contents)
            # we should log if we get count > 1 here!
            for quiz in quizzes:
                num_rand_qs = quiz.numq
                show_answers = quiz.show_answers
                curr_quiz = quiz
                break

            num_qs_to_check = min(questions.count(), num_rand_qs)

            # Function to mark quiz
            num_correct = mark_quiz(user_answers, graded_answers)

            # Calculating quiz score
            correct_pct = Decimal((num_correct / num_qs_to_check) * 100)

            curr_module = None
            quiz_name = "Quiz"
            modules = CourseModule.objects.get(module=mod_nm)
            # we should log if we get count > 1 here!
            # for this_module in modules:
            #     curr_module = this_module
            #     quiz_name = curr_module.title
            #     break
            curr_module = modules
            quiz_name = modules.title

coursebuilder/templates/about.html
<div class="module">
    <h1>
        About the Generic CourseBuilder
    </h1>
    <figure>
        <img src="https://upload.wikimedia.org/wikipedia/commons/2/2e/GNOME_Books_2018.svg">
        <figcaption>
            CourseBuilder
        </figcaption>
    </figure>
    <p>
        A generic website for courses, built by Dr. Eugene
        Callahan, Tirupal Ravilla, Snehal Kenjale, Vishal Tyagi, Avi Patel 
        and Vrajesh Mehta.
    </p>
    <p>
        The course is built using
        <a href="https://www.djangoproject.com">Django</a>
        and other
        <a href="https://github.com/gcallah/CourseBuilder/tree/master/docker/requirements.txt">
            open source tools
        </a>
        and is itself an 
        <a href="https://github.com/gcallah/CourseBuilder">
            open source project.
        </a>
        This website is built using the generic CourseBuilder and depicts how a course would look.
    </p>
    <p>
        The requirements for a A-quality course project are:
    </p>
    <ol class="nested">
        <li>
            The project strictly follows the DRY principle: everything that
            must appear in multiple places in the project has a single
            source.
        </li>
        <li>
            All aspects of the project are under version control, including
            source, build scripts, graphics, documentation, and anything
            else related to the project.
        </li>
        <li>
            Make sure to test changes locally before committing.
        </li>
        <li>
            The project has automated testing with over 50% test coverage,
            and, if web-based, has Selenium tests.
        </li>
        <li>
            All of your code should pass a lint tool for the language
            you are using.
        </li>
        <li>
            For any aspects of the project that are built, there is an
            automated build process.
        </li>
        <li>
            Developers can work in a Docker container for development,
            and deploys can be done via a container. Furthermore, the 
            containers themselves are built by scripts, not by hand.
        </li>
        <li>
            The project can successfully be deployed to the cloud.
        </li>
        <li>
            There is monitoring in place for the project.
        </li>
    </ol>
    <br><br>
</div>

coursebuilder/templates/basics.html
{% extends "dynamic_base.html" %}
{% block content %}

<div class="module" id="basic-content">
        <h1>
            Welcome to CourseBuilder!
        </h1>
</div>






{% endblock content %}

coursebuilder/templates/chapter.html
{% extends "dynamic_base.html" %}
{% block content %}

<div class="module">
    <h1>
        {{ module_title }}
    </h1>
    {% autoescape off %}{{ content }}{% endautoescape %}

    {% for section in sections %}
    <details>
        <summary class="sum1">
            {% if section.lesson_order %}
                {% autoescape off %}
                Lesson {{ section.lesson_order }}: {{ section.title }}
                {% endautoescape %}
            {% else %}
                {% autoescape off %}{{ section.title }}{% endautoescape %}
            {% endif %} 
        </summary>
        {% autoescape off %}{{ section.content }}{% endautoescape %}
    </details>
    {% endfor %}



</div>

{% include 'quiz.html' %}

{% endblock content %}

coursebuilder/templates/dynamic_about.html
{% extends "dynamic_base.html" %}
{% block content %}
    {{message}}
    {% autoescape off %}{{ about }}{% endautoescape %}
{% endblock content %}

coursebuilder/templates/dynamic_base.html
<html>
{% load static %}
<head>
    <title>
        {% block title %}
        {{ header }}
        {% endblock title %}
    </title>
    {% block stylesheets %}
        <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="/static/coursebuilder/styles.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
        <!--Tinymce Text-Editor (Must be in Head Tag) -->
        <script src="{% static 'coursebuilder/js/tinymce/tinymce.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'coursebuilder/js/tinymce/custom.js' %}" ></script>
    {% endblock stylesheets %}
   <script  src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.3.0/fuse.min.js">
   </script>

</head>

<body class="dashboard">
    <div id="container-fluid">
        <div id="header" >
            <div id="user-tools">

                <a href="/" class="header-title">{{ header }}</a>
                <div id="navbar">
                    <a href="/coursebuilder/landing_page/">Home</a>
                &nbsp;&nbsp;
                <a href="/coursebuilder/dynamic_gloss">Glossary</a>

                &nbsp;&nbsp;
                <a href="/coursebuilder/dynamic_about/">About</a>

                &nbsp;&nbsp;
                &nbsp;&nbsp;
                </div>

              <form class="form-inline my-2 my-lg-0"
                  action="{% url 'coursebuilder:parse_search' %}"
                  id="search"
                  style="position: absolute;top:0.75vh;right:6vw;display: none;" >

                  <input class="mr-sm-2 header-search-input"
                  name="query" type="search" aria-label="Search">
                   <button class="header-button">
                          search
                      </button>
                 </form>

                 <button class="header-button" id='bt'
                     style="position: absolute;top:1.2vh;right:3.5vw;">
                          <i class="material-icons "
                              style="margin-bottom: 0.3vh;">search</i>
                 </button>
            </div>
        </div>

        <div id="content" class="container-fluid">
                {% block content %}
                {% endblock content %}
        </div>

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">

    </script>

</body>
<script src="/static/coursebuilder/js/show_searchbar.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>
<script>
    $.support.cors = true;
</script>

</html>

coursebuilder/templates/dynamic_gloss.html
{% extends "dynamic_base.html" %}
{% block content %}
    {{message}}
    {% autoescape off %}{{ gloss }}{% endautoescape %}
{% endblock content %}

coursebuilder/templates/dynamicpage.html
{% extends "dynamic_base.html" %}

{% block content %}

    {% autoescape off %}{{ content }}{% endautoescape %}

{% include 'quiz.html' %}
{% endblock content %}

coursebuilder/templates/graded_quiz.html
{% extends 'dynamic_base.html' %}
{%  load staticfiles %}

{% block title %}Quiz Evaluation{% endblock %}

{% block content %}
<h1>{{ quiz_name }} - Here are your quiz results</h1>
{% if show_answers %}
<ol class="nested">
    {% for graded_answer in graded_answers %}
    <li style="color: #aaf">
        {{ graded_answer.question }}
    </li>
    <p>
        {{ graded_answer.message }}
        The correct answer is:
        {{ graded_answer.correctAnswer}})
        {{ graded_answer.correctAnswerText }}.
    </p>
    {% if graded_answer.status == 'wrong' %}
    <p class="errors">
        You got that one wrong. You answered:
        <br />
        {{ graded_answer.yourAnswer}})
        {{ graded_answer.yourAnswerText }}.
    </p>
    {% endif %}
    {% endfor %}
</ol>
{% else %}
<p>
    <h4> There are no answers available at the moment for this quiz. </h4>
</p>
{% endif %}
<p>
    <br>
    <span>You have correctly answered {{num_correct}} out of {{ num_ques }} questions giving you a score of {{ correct_pct }}%.</span>
</p>

<p>
    {% if navigate_links.previous %}
    <a href={% url 'coursebuilder:chapter' navigate_links.previous %}>
        We suggest you repeat this module
    </a>
    <br />
    {% endif %}
    {% if navigate_links.next %}
    <a href={% url 'coursebuilder:chapter' navigate_links.next %}>
        Continue onto next module
    </a>
    <br />
    {% else %}
    <a href="/">
        Go to home page
    </a>
    <br />
    {% endif %}
</p>
{% endblock %}

coursebuilder/templates/landing_page.html
{% include "dynamic_base.html" %}
<script>
{% comment %} alert('{{message}}') {% endcomment %}
</script>
{% block content %}
    <div class="container-fluid">
     <div class="row">


        <div class="col-sm-5">

          <figure style="margin-top:30%;">
              <img src="https://upload.wikimedia.org/wikipedia/commons/2/2e/GNOME_Books_2018.svg" style="width:50%;">
              <figcaption>
                  <h3>Course</h3>
              </figcaption>
          </figure>
          <br />
          <br />
          <br />
          <br />
          <br />

          
        </div>


         <div class="col-sm-7" style="margin-bottom: 50px;">
              <h1 class="toc_head">
              {{message}}
              </h1>
              
         <ol>
              {% for module in modules %}
                      <li>
                        <a href="/coursebuilder/chapter/{% autoescape off %}{{ module.module }}{% endautoescape %}">
                          {% autoescape off %}{{ module.title }}{% endautoescape %}
                        </a>
                     </li>
              {% endfor %}
        </ol>
       </div>
      </div>

    </div>

{% endblock content %}

coursebuilder/templates/quiz.html
<details {% if messages %} open {% endif %}>
    <summary class="sum1">
        Quiz
    </summary>

    {% if not questions %}
        <ul class="nested">
            <p> There is no quiz available for this module. 
                <br/>
                {% if next_module %}
                    <a href={% url 'coursebuilder:chapter' next_module %}>
                        Continue onto next module
                    </a>
                {% endif %}
            </p>
        </ul>
    {% else %}
        {% if messages %}
            <ul class="errors">
                {% for message in messages %}
                    <li> {{ message }} </li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post" action="{%url 'coursebuilder:grade_quiz'%}" id="formID">
        {% csrf_token %}
            <ol class="nested">

                {% for q in questions %}
                    <div class="card" style="width: 95%;color:black;">

                      <div class="card-body">
                        <p class="quiz_quest">
                            {{ q.text }}
                        </p>
                        <ol class="nested" type='a' >
                        {% if q.answerA %}
                            <li>

                                <input type="radio" name="_{{q.id}}"
                                    value='a' id="{{ q.id }}" required>

                                {{ q.answerA }}
                            </li>
                        {% endif %}
                        {% if q.answerB %}
                            <li>
                                <input type="radio" name="_{{q.id}}"
                                    value='b' >
                                {{ q.answerB }}

                            </li>
                        {% endif %}
                        {% if q.answerC %}
                            <li>
                                <input type="radio" name="_{{q.id}}"
                                    value='c' >
                                 {{ q.answerC }}

                            </li>
                        {% endif %}
                        {% if q.answerD %}
                            <li>
                                <input type="radio" name="_{{q.id}}"
                                    value='d' >
                                    {{ q.answerD }}

                            </li>
                        {% endif %}
                        {% if q.answerE %}
                            <li>
                                <input type="radio" name="_{{q.id}}"
                                    value='e' >
                                   {{ q.answerE }}

                            </li>
                        {% endif %}
                    </ol>
                      </div>
                    </div>


                {% endfor %}
            </ol>
            <p class="submit">
                <button class="btn btn-xl" style='width:30%;'
                    type="submit" name="submit" value="{{mod_nm}}">
                    Grade Quiz
                </button>
            </p>
        </form>
    {% endif %}
</details>

<script src="/static/coursebuilder/js/valid_search_submission.js"> </script>